name: my_di_card
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1
intl:
environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
#  flutter_share: ^2.0.0
  share_plus: ^10.1.4
  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  url_launcher: ^6.3.1
  custom_sliding_segmented_control: ^1.8.5
  google_fonts: ^6.2.1
  http: ^1.3.0
  loader_overlay: ^4.0.0
  fluttertoast: ^8.2.10
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.2
  flutter_localization: ^0.3.1
  sign_in_with_apple: ^6.1.4
  device_info_plus: ^11.2.1
  file_picker: ^8.1.7
  path: ^1.9.0
  dotted_border: ^2.1.0
#  firebase_auth: ^5.5.0
  image_cropper: ^9.0.0
  flex_color_picker: ^3.7.0
  retrofit: any
  dio_cache_interceptor_hive_store: ^3.2.0
  dio_cache_interceptor: ^3.3.0
  equatable: ^2.0.7
  flutter_bloc: ^8.0.1
  dio: ^5.8.0+1
  another_flushbar: ^1.10.26
  shimmer:
  flutter_contacts: ^1.1.9+2
  geocoding:
  app_links: ^6.1.3
  open_filex:
  provider:
  flutter_html:
#  uni_links: ^0.5.1
#  qr: ^3.0.2,
#  flutter_barcode_scanner: ^2.0.0
  ai_barcode_scanner: ^6.0.1
#  google_ml_kit: ^0.7.0  # Check for the latest version on pub.dev

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  retrofit_generator: ^8.2.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/social/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
