name: my_di_card
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  card_swiper: ^3.0.1
  url_launcher: ^6.3.1
  custom_sliding_segmented_control: ^1.8.5
  google_fonts: ^6.2.1
  http: ^1.3.0
  loader_overlay: ^5.0.0
  fluttertoast: ^8.2.10
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  shared_preferences: ^2.4.0
  flutter_spinkit: ^5.2.1
  cached_network_image: ^3.4.1
  google_sign_in: ^6.2.2
  flutter_localization: ^0.3.1
  sign_in_with_apple: ^6.1.4
  device_info_plus: ^11.2.1
  file_picker: ^8.1.7
  path: ^1.9.0
  dotted_border: ^2.1.0
  firebase_auth: ^5.4.1
  image_cropper: ^9.0.0
  flex_color_picker: ^3.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/
    - assets/social/
    - assets/language/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          style: italic
